[2024-12-17 10:20:00,423] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_kafka_producer scheduled__2024-12-16T00:00:00+00:00 [queued]>
[2024-12-17 10:20:00,598] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_kafka_producer scheduled__2024-12-16T00:00:00+00:00 [queued]>
[2024-12-17 10:20:00,598] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-17 10:20:00,631] {taskinstance.py:1357} INFO - Starting attempt 4 of 4
[2024-12-17 10:20:00,631] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-17 10:20:00,823] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): start_kafka_producer> on 2024-12-16 00:00:00+00:00
[2024-12-17 10:20:00,831] {standard_task_runner.py:52} INFO - Started process 221 to run task
[2024-12-17 10:20:00,866] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'start_kafka_producer', 'scheduled__2024-12-16T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/tmp/tmphxu1njmq', '--error-file', '/tmp/tmpflvmjlb8']
[2024-12-17 10:20:00,874] {standard_task_runner.py:80} INFO - Job 52: Subtask start_kafka_producer
[2024-12-17 10:20:00,992] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-17 10:20:01,567] {task_command.py:369} INFO - Running <TaskInstance: weather_data_pipeline.start_kafka_producer scheduled__2024-12-16T00:00:00+00:00 [running]> on host 9f48f82522d1
[2024-12-17 10:20:03,030] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=bouchra
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=start_kafka_producer
AIRFLOW_CTX_EXECUTION_DATE=2024-12-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-16T00:00:00+00:00
[2024-12-17 10:20:03,035] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-17 10:20:03,060] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker exec spark-streaming python3 /app/producer.py']
[2024-12-17 10:20:03,189] {subprocess.py:85} INFO - Output:
[2024-12-17 10:20:03,306] {subprocess.py:92} INFO - bash: line 1: docker: command not found
[2024-12-17 10:20:03,308] {subprocess.py:96} INFO - Command exited with return code 127
[2024-12-17 10:20:03,504] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-17 10:20:03,581] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=weather_data_pipeline, task_id=start_kafka_producer, execution_date=20241216T000000, start_date=20241217T102000, end_date=20241217T102003
[2024-12-17 10:20:03,745] {standard_task_runner.py:97} ERROR - Failed to execute job 52 for task start_kafka_producer (Bash command failed. The command returned a non-zero exit code 127.; 221)
[2024-12-17 10:20:03,864] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-12-17 10:20:04,248] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
