[2024-12-16 15:50:46,996] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_containers manual__2024-12-16T15:37:06.571115+00:00 [queued]>
[2024-12-16 15:50:47,009] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_containers manual__2024-12-16T15:37:06.571115+00:00 [queued]>
[2024-12-16 15:50:47,010] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 15:50:47,037] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2024-12-16 15:50:47,038] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 15:50:47,093] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): start_containers> on 2024-12-16 15:37:06.571115+00:00
[2024-12-16 15:50:47,100] {standard_task_runner.py:52} INFO - Started process 354 to run task
[2024-12-16 15:50:47,106] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'start_containers', 'manual__2024-12-16T15:37:06.571115+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/tmp/tmpimefxw1w', '--error-file', '/tmp/tmp7jn6x90p']
[2024-12-16 15:50:47,114] {standard_task_runner.py:80} INFO - Job 23: Subtask start_containers
[2024-12-16 15:50:47,233] {task_command.py:369} INFO - Running <TaskInstance: weather_data_pipeline.start_containers manual__2024-12-16T15:37:06.571115+00:00 [running]> on host 975e3760f96f
[2024-12-16 15:50:47,439] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=bouchra
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=start_containers
AIRFLOW_CTX_EXECUTION_DATE=2024-12-16T15:37:06.571115+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-16T15:37:06.571115+00:00
[2024-12-16 15:50:47,443] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-16 15:50:47,445] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker-compose up -d']
[2024-12-16 15:50:47,456] {subprocess.py:85} INFO - Output:
[2024-12-16 15:50:47,458] {subprocess.py:92} INFO - bash: line 1: docker-compose: command not found
[2024-12-16 15:50:47,459] {subprocess.py:96} INFO - Command exited with return code 127
[2024-12-16 15:50:47,490] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-16 15:50:47,497] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_pipeline, task_id=start_containers, execution_date=20241216T153706, start_date=20241216T155046, end_date=20241216T155047
[2024-12-16 15:50:47,532] {standard_task_runner.py:97} ERROR - Failed to execute job 23 for task start_containers (Bash command failed. The command returned a non-zero exit code 127.; 354)
[2024-12-16 15:50:47,567] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-12-16 15:50:47,649] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
