[2024-12-16 15:58:11,720] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_kafka_producer manual__2024-12-16T15:58:06.954248+00:00 [queued]>
[2024-12-16 15:58:11,759] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_kafka_producer manual__2024-12-16T15:58:06.954248+00:00 [queued]>
[2024-12-16 15:58:11,759] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 15:58:11,760] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2024-12-16 15:58:11,761] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 15:58:11,876] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): start_kafka_producer> on 2024-12-16 15:58:06.954248+00:00
[2024-12-16 15:58:11,882] {standard_task_runner.py:52} INFO - Started process 206 to run task
[2024-12-16 15:58:11,887] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'start_kafka_producer', 'manual__2024-12-16T15:58:06.954248+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/tmp/tmpur8o19rv', '--error-file', '/tmp/tmplahjsrnh']
[2024-12-16 15:58:11,894] {standard_task_runner.py:80} INFO - Job 28: Subtask start_kafka_producer
[2024-12-16 15:58:12,243] {task_command.py:369} INFO - Running <TaskInstance: weather_data_pipeline.start_kafka_producer manual__2024-12-16T15:58:06.954248+00:00 [running]> on host 975e3760f96f
[2024-12-16 15:58:14,363] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=bouchra
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=start_kafka_producer
AIRFLOW_CTX_EXECUTION_DATE=2024-12-16T15:58:06.954248+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-16T15:58:06.954248+00:00
[2024-12-16 15:58:14,427] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-16 15:58:14,439] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker exec spark-streaming python3 /app/producer.py']
[2024-12-16 15:58:14,488] {subprocess.py:85} INFO - Output:
[2024-12-16 15:58:14,752] {subprocess.py:92} INFO - bash: line 1: docker: command not found
[2024-12-16 15:58:14,755] {subprocess.py:96} INFO - Command exited with return code 127
[2024-12-16 15:58:14,869] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-16 15:58:14,928] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_pipeline, task_id=start_kafka_producer, execution_date=20241216T155806, start_date=20241216T155811, end_date=20241216T155814
[2024-12-16 15:58:15,044] {standard_task_runner.py:97} ERROR - Failed to execute job 28 for task start_kafka_producer (Bash command failed. The command returned a non-zero exit code 127.; 206)
[2024-12-16 15:58:15,141] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-12-16 15:58:15,342] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
