[2024-12-16 15:04:10,314] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_kafka_producer scheduled__2024-12-15T00:00:00+00:00 [queued]>
[2024-12-16 15:04:10,338] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_kafka_producer scheduled__2024-12-15T00:00:00+00:00 [queued]>
[2024-12-16 15:04:10,348] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 15:04:10,350] {taskinstance.py:1357} INFO - Starting attempt 3 of 4
[2024-12-16 15:04:10,354] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 15:04:10,444] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): start_kafka_producer> on 2024-12-15 00:00:00+00:00
[2024-12-16 15:04:10,448] {standard_task_runner.py:52} INFO - Started process 173 to run task
[2024-12-16 15:04:10,478] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'start_kafka_producer', 'scheduled__2024-12-15T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/tmp/tmpk5f75zy0', '--error-file', '/tmp/tmp93svg_g6']
[2024-12-16 15:04:10,481] {standard_task_runner.py:80} INFO - Job 10: Subtask start_kafka_producer
[2024-12-16 15:04:10,581] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-16 15:04:10,770] {task_command.py:369} INFO - Running <TaskInstance: weather_data_pipeline.start_kafka_producer scheduled__2024-12-15T00:00:00+00:00 [running]> on host e332481b8716
[2024-12-16 15:04:11,271] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=bouchra
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=start_kafka_producer
AIRFLOW_CTX_EXECUTION_DATE=2024-12-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-15T00:00:00+00:00
[2024-12-16 15:04:11,274] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-16 15:04:11,291] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker exec spark-streaming python3 /app/producer.py']
[2024-12-16 15:04:11,333] {subprocess.py:85} INFO - Output:
[2024-12-16 15:04:11,342] {subprocess.py:92} INFO - bash: line 1: docker: command not found
[2024-12-16 15:04:11,343] {subprocess.py:96} INFO - Command exited with return code 127
[2024-12-16 15:04:11,427] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-16 15:04:11,442] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_pipeline, task_id=start_kafka_producer, execution_date=20241215T000000, start_date=20241216T150410, end_date=20241216T150411
[2024-12-16 15:04:11,514] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task start_kafka_producer (Bash command failed. The command returned a non-zero exit code 127.; 173)
[2024-12-16 15:04:11,533] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-12-16 15:04:11,767] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
