[2024-12-16 15:37:07,845] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_kafka_producer manual__2024-12-16T15:37:06.571115+00:00 [queued]>
[2024-12-16 15:37:07,904] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_kafka_producer manual__2024-12-16T15:37:06.571115+00:00 [queued]>
[2024-12-16 15:37:07,905] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 15:37:07,932] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2024-12-16 15:37:07,932] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 15:37:08,012] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): start_kafka_producer> on 2024-12-16 15:37:06.571115+00:00
[2024-12-16 15:37:08,021] {standard_task_runner.py:52} INFO - Started process 210 to run task
[2024-12-16 15:37:08,027] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'start_kafka_producer', 'manual__2024-12-16T15:37:06.571115+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/tmp/tmpjam3yt2x', '--error-file', '/tmp/tmpecl9ssci']
[2024-12-16 15:37:08,039] {standard_task_runner.py:80} INFO - Job 20: Subtask start_kafka_producer
[2024-12-16 15:37:08,185] {task_command.py:369} INFO - Running <TaskInstance: weather_data_pipeline.start_kafka_producer manual__2024-12-16T15:37:06.571115+00:00 [running]> on host 975e3760f96f
[2024-12-16 15:37:08,405] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=bouchra
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=start_kafka_producer
AIRFLOW_CTX_EXECUTION_DATE=2024-12-16T15:37:06.571115+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-16T15:37:06.571115+00:00
[2024-12-16 15:37:08,407] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-16 15:37:08,408] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker exec spark-streaming python3 /app/producer.py']
[2024-12-16 15:37:08,421] {subprocess.py:85} INFO - Output:
[2024-12-16 15:37:08,426] {subprocess.py:92} INFO - bash: line 1: docker: command not found
[2024-12-16 15:37:08,428] {subprocess.py:96} INFO - Command exited with return code 127
[2024-12-16 15:37:08,477] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-16 15:37:08,488] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_pipeline, task_id=start_kafka_producer, execution_date=20241216T153706, start_date=20241216T153707, end_date=20241216T153708
[2024-12-16 15:37:08,516] {standard_task_runner.py:97} ERROR - Failed to execute job 20 for task start_kafka_producer (Bash command failed. The command returned a non-zero exit code 127.; 210)
[2024-12-16 15:37:08,569] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-12-16 15:37:08,785] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
