[2024-12-16 15:54:52,995] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_kafka_producer manual__2024-12-16T15:37:06.571115+00:00 [queued]>
[2024-12-16 15:54:53,075] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_kafka_producer manual__2024-12-16T15:37:06.571115+00:00 [queued]>
[2024-12-16 15:54:53,076] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 15:54:53,077] {taskinstance.py:1357} INFO - Starting attempt 4 of 4
[2024-12-16 15:54:53,077] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 15:54:53,153] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): start_kafka_producer> on 2024-12-16 15:37:06.571115+00:00
[2024-12-16 15:54:53,159] {standard_task_runner.py:52} INFO - Started process 172 to run task
[2024-12-16 15:54:53,175] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'start_kafka_producer', 'manual__2024-12-16T15:37:06.571115+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/tmp/tmp9zt8c2g6', '--error-file', '/tmp/tmpxtq8nolw']
[2024-12-16 15:54:53,185] {standard_task_runner.py:80} INFO - Job 26: Subtask start_kafka_producer
[2024-12-16 15:54:53,385] {task_command.py:369} INFO - Running <TaskInstance: weather_data_pipeline.start_kafka_producer manual__2024-12-16T15:37:06.571115+00:00 [running]> on host 975e3760f96f
[2024-12-16 15:54:53,618] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=bouchra
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=start_kafka_producer
AIRFLOW_CTX_EXECUTION_DATE=2024-12-16T15:37:06.571115+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-16T15:37:06.571115+00:00
[2024-12-16 15:54:53,620] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-16 15:54:53,628] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker exec spark-streaming python3 /app/producer.py']
[2024-12-16 15:54:53,645] {subprocess.py:85} INFO - Output:
[2024-12-16 15:54:53,660] {subprocess.py:92} INFO - bash: line 1: docker: command not found
[2024-12-16 15:54:53,661] {subprocess.py:96} INFO - Command exited with return code 127
[2024-12-16 15:54:53,782] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-16 15:54:53,792] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=weather_data_pipeline, task_id=start_kafka_producer, execution_date=20241216T153706, start_date=20241216T155453, end_date=20241216T155453
[2024-12-16 15:54:53,875] {standard_task_runner.py:97} ERROR - Failed to execute job 26 for task start_kafka_producer (Bash command failed. The command returned a non-zero exit code 127.; 172)
[2024-12-16 15:54:53,913] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-12-16 15:54:54,022] {dagrun.py:648} WARNING - Failed to get task '<TaskInstance: weather_data_pipeline.start_containers manual__2024-12-16T15:37:06.571115+00:00 [removed]>' for dag 'weather_data_pipeline'. Marking it as removed.
[2024-12-16 15:54:54,065] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
