[2024-12-16 14:54:01,814] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_kafka_producer manual__2024-12-16T14:54:00.661362+00:00 [queued]>
[2024-12-16 14:54:01,829] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_kafka_producer manual__2024-12-16T14:54:00.661362+00:00 [queued]>
[2024-12-16 14:54:01,830] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 14:54:01,831] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2024-12-16 14:54:01,832] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 14:54:01,862] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): start_kafka_producer> on 2024-12-16 14:54:00.661362+00:00
[2024-12-16 14:54:01,867] {standard_task_runner.py:52} INFO - Started process 251 to run task
[2024-12-16 14:54:01,872] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'start_kafka_producer', 'manual__2024-12-16T14:54:00.661362+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/tmp/tmpfm77hy6o', '--error-file', '/tmp/tmp3imxvh08']
[2024-12-16 14:54:01,874] {standard_task_runner.py:80} INFO - Job 5: Subtask start_kafka_producer
[2024-12-16 14:54:01,951] {task_command.py:369} INFO - Running <TaskInstance: weather_data_pipeline.start_kafka_producer manual__2024-12-16T14:54:00.661362+00:00 [running]> on host bac2eaa32d25
[2024-12-16 14:54:02,106] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=bouchra
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=start_kafka_producer
AIRFLOW_CTX_EXECUTION_DATE=2024-12-16T14:54:00.661362+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-16T14:54:00.661362+00:00
[2024-12-16 14:54:02,110] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-16 14:54:02,111] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker exec spark-streaming python3 /app/producer.py']
[2024-12-16 14:54:02,124] {subprocess.py:85} INFO - Output:
[2024-12-16 14:54:02,127] {subprocess.py:92} INFO - bash: line 1: docker: command not found
[2024-12-16 14:54:02,127] {subprocess.py:96} INFO - Command exited with return code 127
[2024-12-16 14:54:02,150] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-16 14:54:02,158] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_pipeline, task_id=start_kafka_producer, execution_date=20241216T145400, start_date=20241216T145401, end_date=20241216T145402
[2024-12-16 14:54:02,188] {standard_task_runner.py:97} ERROR - Failed to execute job 5 for task start_kafka_producer (Bash command failed. The command returned a non-zero exit code 127.; 251)
[2024-12-16 14:54:02,204] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-12-16 14:54:02,269] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
