[2024-12-16 14:59:02,475] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_kafka_producer manual__2024-12-16T14:54:00.661362+00:00 [queued]>
[2024-12-16 14:59:02,487] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.start_kafka_producer manual__2024-12-16T14:54:00.661362+00:00 [queued]>
[2024-12-16 14:59:02,488] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 14:59:02,488] {taskinstance.py:1357} INFO - Starting attempt 2 of 4
[2024-12-16 14:59:02,489] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 14:59:02,508] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): start_kafka_producer> on 2024-12-16 14:54:00.661362+00:00
[2024-12-16 14:59:02,512] {standard_task_runner.py:52} INFO - Started process 307 to run task
[2024-12-16 14:59:02,516] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'start_kafka_producer', 'manual__2024-12-16T14:54:00.661362+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/tmp/tmpdjw02n36', '--error-file', '/tmp/tmpmz86wl1v']
[2024-12-16 14:59:02,517] {standard_task_runner.py:80} INFO - Job 7: Subtask start_kafka_producer
[2024-12-16 14:59:02,576] {task_command.py:369} INFO - Running <TaskInstance: weather_data_pipeline.start_kafka_producer manual__2024-12-16T14:54:00.661362+00:00 [running]> on host bac2eaa32d25
[2024-12-16 14:59:02,656] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=bouchra
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=start_kafka_producer
AIRFLOW_CTX_EXECUTION_DATE=2024-12-16T14:54:00.661362+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-16T14:54:00.661362+00:00
[2024-12-16 14:59:02,657] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-16 14:59:02,658] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker exec spark-streaming python3 /app/producer.py']
[2024-12-16 14:59:02,665] {subprocess.py:85} INFO - Output:
[2024-12-16 14:59:02,667] {subprocess.py:92} INFO - bash: line 1: docker: command not found
[2024-12-16 14:59:02,668] {subprocess.py:96} INFO - Command exited with return code 127
[2024-12-16 14:59:02,687] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-16 14:59:02,691] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_pipeline, task_id=start_kafka_producer, execution_date=20241216T145400, start_date=20241216T145902, end_date=20241216T145902
[2024-12-16 14:59:02,706] {standard_task_runner.py:97} ERROR - Failed to execute job 7 for task start_kafka_producer (Bash command failed. The command returned a non-zero exit code 127.; 307)
[2024-12-16 14:59:02,728] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-12-16 14:59:02,774] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
